dist: Bionic
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
env:
  - product_filename="HMP-kernel-*.zip" chat_id="-1001115967921"
install: |
  sudo apt-get install flex bison build-essential zip zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libx11-dev ccache libgl1-mesa-dev libxml2-utils xsltproc bc imagemagick libssl-dev mc libncurses5 python
  git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 -b lineage-17.0 ~/gcc
before_script: |
  sudo apt install python3-setuptools python3-pip git
  git clone https://github.com/RomashkaGang/PublishBot
  pip3 install --user -r PublishBot/requirements.txt
  python3 PublishBot/main.py --before
script: |
  make O=out ARCH=arm64 platina_defconfig
  make -j8 O=out ARCH=arm64 CROSS_COMPILE=~/gcc/bin/aarch64-linux-android-
  git clone https://github.com/RomashkaGang/AnyKernel3 ~/kernel_done
  if [ -f "out/arch/arm64/boot/Image.gz-dtb" ]; then
    cp out/arch/arm64/boot/Image.gz-dtb ~/kernel_done
    cd ~/kernel_done
    export FILENAME="HMP-kernel-$(date +"%m%d%y")-$(date +"%H%M").zip"
    zip -r9 $FILENAME * -x .git $FILENAME
  fi
after_success: |
  python3 PublishBot/main.py --after
after_failure: |
  python3 PublishBot/main.py --after
